name: expense_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.15+70

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3
  path: ^1.9.0
  fl_chart: ^0.67.0
  collection: ^1.18.0
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.0.10+1
  flutter_slidable: ^3.1.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  flutter_timezone: ^1.0.8
  in_app_review: ^2.0.9
  app_settings: ^5.1.1
  home_widget: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: '#000C33'
  image: 'assets/icon/AppIcon.png'

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/flags/
    - assets/logo/
    - assets/icon/
    - lib/Configuration/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-L.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu-R.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-RI.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Ubuntu-M.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-MI.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-B.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-BI.ttf
          weight: 700
          style: italic
        
       